#!/usr/bin/env bash
# ktags guard — small mechanical checks shared by git hooks, Claude hooks and CI.
#
#   guard.sh doctor [--quiet]            tools present, hooks active, gh auth, HEAD clean of attribution
#   guard.sh check-message <file>        commit-msg hook: reject AI attribution in a message file
#   guard.sh check-tool-input            Claude PreToolUse hook: reads tool JSON on stdin, rejects
#                                        attribution inside a `git commit` command (exit 2 blocks)
#   guard.sh verify-attribution <range>  scan commit messages in a git range (CI, review)
#
# Exit codes: 0 ok · 1 usage · 2 blocking finding (also the Claude hook "block" code) · 3 environment
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Case-insensitive. Kept in one place; docs/workflow.md points here.
ATTRIBUTION_RE='co-authored-by:.*(claude|anthropic|openai|codex|chatgpt|copilot|gemini|opencode|cursor|noreply@anthropic|noreply@openai)|generated with|generated by (claude|codex|chatgpt|copilot|gemini|ai)|claude-session|🤖'

die() { echo "guard: $1" >&2; exit "${2:-1}"; }

scan_text() {
  # $1 = text; prints matching lines, returns 0 if any matched
  printf '%s\n' "$1" | grep -iE "$ATTRIBUTION_RE" || return 1
}

cmd_check_message() {
  local file="${1:-}"
  [[ -n "$file" && -r "$file" ]] || die "check-message needs a readable message file" 1
  local body
  body="$(grep -v '^#' "$file" || true)"
  if hits="$(scan_text "$body")"; then
    echo "guard: AI attribution is not allowed in commit messages (AGENTS.md → Hard rules):" >&2
    echo "$hits" | sed 's/^/  /' >&2
    exit 2
  fi
}

cmd_check_tool_input() {
  # Claude Code PreToolUse hook. stdin: JSON with .tool_input.command
  local input cmd
  input="$(cat)"
  if command -v jq >/dev/null 2>&1; then
    cmd="$(printf '%s' "$input" | jq -r '.tool_input.command // empty')"
  else
    cmd="$input"
  fi
  [[ -n "$cmd" ]] || exit 0
  if hits="$(scan_text "$cmd")"; then
    echo "AI attribution is not allowed in commit messages (AGENTS.md → Hard rules). Remove:" >&2
    echo "$hits" | sed 's/^/  /' >&2
    exit 2
  fi
}

cmd_verify_attribution() {
  local range="${1:-}"
  [[ -n "$range" ]] || die "verify-attribution needs a git range, e.g. origin/main..HEAD" 1
  # Fail closed: an unresolvable range must not read as "clean".
  local shas
  shas="$(git -C "$ROOT" rev-list "$range")" || die "cannot resolve range '$range'" 3
  local bad=0 n=0 sha msg
  for sha in $shas; do
    n=$((n + 1))
    msg="$(git -C "$ROOT" log -1 --format='%B' "$sha")"
    if hits="$(scan_text "$msg")"; then
      echo "guard: attribution in commit ${sha:0:12}:" >&2
      echo "$hits" | sed 's/^/  /' >&2
      bad=1
    fi
  done
  [[ $bad -eq 0 ]] || exit 2
  echo "guard: no attribution in $n commit(s) of $range"
}

cmd_doctor() {
  local quiet=0; [[ "${1:-}" == "--quiet" ]] && quiet=1
  local rc=0
  ok()   { [[ $quiet -eq 1 ]] || echo "  ok    $1"; }
  warn() { echo "  WARN  $1" >&2; }
  fail() { echo "  FAIL  $1" >&2; rc=3; }

  [[ $quiet -eq 1 ]] || echo "ktags guard doctor"
  for t in go git gh python3; do
    command -v "$t" >/dev/null 2>&1 && ok "$t $(command -v "$t")" || fail "$t missing"
  done
  command -v golangci-lint >/dev/null 2>&1 && ok "golangci-lint" || warn "golangci-lint missing (brew install golangci-lint)"
  command -v jq >/dev/null 2>&1 && ok "jq" || warn "jq missing (brew install jq); Claude commit hook falls back to raw scan"

  local hp
  hp="$(git -C "$ROOT" config --get core.hooksPath || true)"
  if [[ "$hp" == ".githooks" || "$hp" == "$ROOT/.githooks" ]]; then
    ok "git hooks active (core.hooksPath=$hp)"
  else
    fail "git hooks inactive — run: make hooks"
  fi
  for hook in pre-commit commit-msg pre-push; do
    [[ -x "$ROOT/.githooks/$hook" ]] || fail "$hook hook not executable — run: make hooks"
  done

  if gh auth status >/dev/null 2>&1; then ok "gh authenticated"; else warn "gh not authenticated (gh auth login)"; fi

  if git -C "$ROOT" rev-parse HEAD >/dev/null 2>&1; then
    if hits="$(scan_text "$(git -C "$ROOT" log -1 --format='%B' HEAD)")"; then
      fail "HEAD commit carries attribution"
    else
      ok "HEAD commit clean"
    fi
  fi

  if [[ -n "$(git -C "$ROOT" status --porcelain)" ]]; then
    [[ $quiet -eq 1 ]] || warn "working tree has uncommitted changes"
  fi
  exit $rc
}

case "${1:-}" in
  doctor)              shift; cmd_doctor "$@" ;;
  check-message)       shift; cmd_check_message "$@" ;;
  check-tool-input)    shift; cmd_check_tool_input "$@" ;;
  verify-attribution)  shift; cmd_verify_attribution "$@" ;;
  *) sed -n '2,10p' "$0" >&2; exit 1 ;;
esac
